name: Xposed Release Build

on:
  workflow_dispatch: # 手动触发
  push:
    tags: [ "v*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MODULE_NAME: "xposed"  # 明确指定模块名称

    steps:
    - uses: actions/checkout@v4

    - name: Setup Signing
      env:
        SIGNING_KEY_BASE64: ${{ secrets.XPOSED_SIGNING_KEY_BASE64 }}  # 单独为xposed模块配置
      run: |
        mkdir -p $MODULE_NAME
        echo "$SIGNING_KEY_BASE64" | base64 -d > $MODULE_NAME/module.jks  # 与脚本中的路径匹配

    - name: Validate Keystore
      run: |
        file $MODULE_NAME/module.jks  # 验证文件类型
        keytool -list -v -keystore $MODULE_NAME/module.jks -storepass ${{ secrets.XPOSED_STORE_PASSWORD }}

    - name: Build Release
      env:
        ORG_GRADLE_PROJECT_storeFile: "$MODULE_NAME/module.jks"  # Gradle属性注入
        ORG_GRADLE_PROJECT_storePassword: "${{ secrets.XPOSED_STORE_PASSWORD }}"
        ORG_GRADLE_PROJECT_keyAlias: "${{ secrets.XPOSED_KEY_ALIAS }}"
        ORG_GRADLE_PROJECT_keyPassword: "${{ secrets.XPOSED_KEY_PASSWORD }}"
      run: |
        ./gradlew :$MODULE_NAME:assembleRelease --stacktrace
        ls -l $MODULE_NAME/build/outputs/apk/release/

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: xposed-release
        path: ${{ env.MODULE_NAME }}/build/outputs/apk/release/*.apk
